version: "3"
services:
    server:
        image: funkgeraet_server
        build:
            context: .
            dockerfile: server/Dockerfile
        ports:
            - "6503:6503"
    client:
        image: funkgeraet_client
        environment:
            - WEB_SOCKET_SERVER_URL=localhost:6503
            - ICE_SERVERS=[{\"urls\":\"stun:stunserver.org:3478\"}]
        build:
            context: .
            dockerfile: client/Dockerfile
        ports:
            - "80:80"
