version: "3"
services:
    server:
        image: ghcr.io/debugger-buam/funkgeraet_server
        restart: always
        ports:
            - "6503:6503"
    client:
        image: ghcr.io/debugger-buam/funkgeraet_client
        restart: always
        environment:
            - WEB_SOCKET_SERVER_URL=localhost:6503
            - ICE_SERVERS=[{\"urls\":\"stun:stunserver.org:3478\"}]
        ports:
            - "80:80"
