# Source: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs
name: Frontend CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
#    - run: npm test
#      env:
#        CI: true

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Docker
      run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_PASSWORD }}
    - name: Move env file
      run: mv -n client/.env.example client/.env
    - name: Build Image
      run: docker-compose build client
    - name: Tag Image
      run: docker image tag funkgeraet_client ghcr.io/${{ secrets.GHCR_USERNAME }}/funkgeraet_client
    - name: Publish Image
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/funkgeraet_client:latest
     
