name: Publish Frontend Image

on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Push Docker image to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: ./client/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/debugger-buam/funkgeraet_client
