name: Build and Publish Docker Image

on: [push]

jobs:
  build:
    runs-on: docker:latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Docker compose
      run: apk add --update py-pip
      run: pip install docker-compose
    - name: Build Image
      run: docker-compose build client
    - name: Publish Image
      run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_PASSWORD }}
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/$GITHUB_REPOSITORY:latest
     